### ISSUE TITLE
Direct link to /posts/:slug gives 404

### ISSUE THREAD

**Issue by halol** [datocms/nuxtjs-demo#7]
Hi, I really like the demo and it helped me understand some of the concepts of using DatoCMS. However, opening a permalink to the post gives 404 on Netlify. Try opening https://datocms-nuxtjs-demo.netlify.app/posts/mistakes-tourists-make-on-their-first-trip-abroad

![image](https://user-images.githubusercontent.com/2233348/108967201-79b8a400-767f-11eb-9ef4-d99643d6350f.png)

It looks that it works on localhost and params with `slug` is passed properly (even in the incognito mode).

I tried to have a fallback for the GQL query where the `slug` variable is present:

```slug: this.$route.params.slug || this.$route.path.replace("/folder/", "") // to get only the slug if the params are empty```

**Comment by stefanoverna** [comment]
This line on the config file fixes the issue! https://github.com/datocms/nuxtjs-demo/commit/4ce03c0352d312b7fd0a7f277fb0a6ed219b241b
